package:
  name: kissfft-mojo
  version: "0.1.0"

source:
  path: .

build:
  number: 0
  script:
    - mkdir -p $PREFIX/lib/mojo
    - export MODULAR_HOME=$BUILD_PREFIX/share/max
    - mojo package kissfft -o $PREFIX/lib/mojo/kissfft.mojopkg

requirements:
  build:
    - mojo >=0.25.7.0.dev2025110305,<0.26
    - max >=25.7.0.dev2025110305,<26
  run:
    - mojo >=0.25.7.0.dev2025110305,<0.26
    - max >=25.7.0.dev2025110305,<26
