package:
  name: glfw-mojo
  version: "0.1.0"

source:
  path: .

build:
  number: 0
  script:
    - mkdir -p $PREFIX/lib/mojo
    - export MODULAR_HOME=$BUILD_PREFIX/share/max
    - mojo package glfw -o $PREFIX/lib/mojo/glfw.mojopkg -I $PREFIX/lib/mojo/

requirements:
  build:
    - ffipointer
  run:
    - ffipointer
