package:
  name: ffipointer
  version: "0.1.0"

source:
  path: .

build:
  number: 0
  script:
    - mkdir -p $PREFIX/lib/mojo
    - export MODULAR_HOME=$BUILD_PREFIX/share/max
    - mojo package ffipointer -o $PREFIX/lib/mojo/ffipointer.mojopkg

requirements:
  build:
    - max >=26.0
  run:
    - max >=26.0
